version: "3.7"
services:
  app:
    build:
      args:
        user: datata
        uid: 1000
      context: ./php
      dockerfile: Dockerfile
    # image: php:7.4-fpm
    container_name: the-final-count-days-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./the_final_count_days_app:/var/www
    networks:
      - the-final-count-days

  nginx:
    image: nginx:1.17-alpine
    container_name: the-final-count-days-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./the_final_count_days_app:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - the-final-count-days

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - the-final-count-days

  db:
    image: mysql:5.7
    container_name: the-final-count-days-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: the_final_count_days_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - the-final-count-days  

networks:
  the-final-count-days:
    driver: bridge